name: Dentrix Adapter

on:
  push:
    branches:
      - staging
      - bootstrap

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install AzureSignTool
        run: dotnet tool install --global AzureSignTool

      - name: Build Projects
        run: |
          dotnet build --configuration:Staging --property:"Platform=x86;PlatformTarget=x86" --arch:x86 Gain
          dotnet build --configuration:Staging --property:"Platform=x86;PlatformTarget=x86" --arch:x86 GainService
          dotnet build --configuration:Staging --property:"Platform=x86;PlatformTarget=x86" --arch:x86 DentrixDlg
          dotnet build --configuration:Staging --property:"Platform=x86;PlatformTarget=x86" --arch:x86 Installer

          dotnet build --configuration:Staging --property:"Platform=x64;PlatformTarget=x64" --arch:x64 Gain
          dotnet build --configuration:Staging --property:"Platform=x64;PlatformTarget=x64" --arch:x64 GainService
          dotnet build --configuration:Staging --property:"Platform=x64;PlatformTarget=x64" --arch:x64 DentrixDlg
          dotnet build --configuration:Staging --property:"Platform=x64;PlatformTarget=x64" --arch:x64 Installer

      - name: Sign Projects
        run: >
          AzureSignTool sign
          -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}"
          -kvt "${{ secrets.AZURE_TENANT_ID }}"
          -kvi "${{ secrets.AZURE_CLIENT_ID }}"
          -kvs "${{ secrets.AZURE_CLIENT_SECRET }}"
          -kvc "${{ secrets.AZURE_CERT_NAME }}"
          -tr http://timestamp.digicert.com
          -v
          Gain/bin/Staging/**/*.dll
          Gain/bin/Staging/**/*.exe
          GainService/bin/Staging/**/*.dll
          GainService/bin/Staging/**/*.exe
          DentrixDlg/bin/Staging/**/*.dll
          DentrixDlg/bin/Staging/**/*.exe
          Installer/bin/Staging/**/*.msi

      - name: Build Bootstrapper
        run: |
          # https://wixtoolset.org/docs/development/wips/replace-win64-with-intuitive-attribute/
          dotnet build --configuration:Staging --property:"Platform=x86;PlatformTarget=x86" --arch:x86 Bootstrapper
          dotnet build --configuration:Staging --property:"Platform=x64;PlatformTarget=x64" --arch:x64 Bootstrapper

      - name: Sign Bootstrappers
        run: >
          AzureSignTool sign
          -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}"
          -kvt "${{ secrets.AZURE_TENANT_ID }}"
          -kvi "${{ secrets.AZURE_CLIENT_ID }}"
          -kvs "${{ secrets.AZURE_CLIENT_SECRET }}"
          -kvc "${{ secrets.AZURE_CERT_NAME }}"
          -tr http://timestamp.digicert.com
          -v
          Bootstrapper/bin/Staging/**/*.exe

      - name: Upload Bundle (x86)
        uses: actions/upload-artifact@v4
        with:
          name: Bootstrapper (x86).msi
          path: Bootstrapper/bin/Staging/x86/Bootstrapper.exe

      - name: Upload Bundle (x64)
        uses: actions/upload-artifact@v4
        with:
          name: Bootstrapper (x64).msi
          path: Bootstrapper/bin/Staging/x64/Bootstrapper.exe
