name: Dentrix Adapter

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install AzureSignTool
        run: dotnet tool install --global AzureSignTool

      - name: Build Projects
        run: |
          dotnet build --configuration:Staging --property:"Platform=x86;PlatformTarget=x86" --arch:x86 GainPackage
          dotnet build --configuration:Staging --property:"Platform=x64;PlatformTarget=x64" --arch:x64 GainPackage

      - name: Sign Projects
        run: >
          AzureSignTool sign
          -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}"
          -kvt "${{ secrets.AZURE_TENANT_ID }}"
          -kvi "${{ secrets.AZURE_CLIENT_ID }}"
          -kvs "${{ secrets.AZURE_CLIENT_SECRET }}"
          -kvc "${{ secrets.AZURE_CERT_NAME }}"
          -tr http://timestamp.digicert.com
          -v
          */bin/Staging/**/*.dll
          */bin/Staging/**/*.exe
          */bin/Staging/**/*.msi

      - name: Build Installers
        run: |
          # https://wixtoolset.org/docs/development/wips/replace-win64-with-intuitive-attribute/
          dotnet build --configuration:Staging --property:"Platform=x86;PlatformTarget=x86" --arch:x86 GainInstaller
          dotnet build --configuration:Staging --property:"Platform=x64;PlatformTarget=x64" --arch:x64 GainInstaller

      - name: Upload Installer (x86)
        uses: actions/upload-artifact@v4
        with:
          name: Gain Installer (x86)
          path: GainInstaller/bin/Staging/x86/GainInstaller.exe

      - name: Upload Installer (x64)
        uses: actions/upload-artifact@v4
        with:
          name: Gain Installer (x64)
          path: GainInstaller/bin/Staging/x64/GainInstaller.exe
